# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Feeder06', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_y',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
