# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feeder06', '0006_importform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('deadline', models.CharField(max_length=50)),
                ('running', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='endsem_date',
            field=models.CharField(default='Not yet decided', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='midsem_date',
            field=models.CharField(default='Not yet decided', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deadline',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Feeder06.Course'),
        ),
    ]
