# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feeder06', '0008_feedbackform_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('last_date', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Feeder06.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='feedbackform',
            name='course',
        ),
        migrations.AlterField(
            model_name='question',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Feeder06.Feedback'),
        ),
        migrations.DeleteModel(
            name='FeedbackForm',
        ),
    ]
