# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feeder06', '0009_auto_20161102_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='endsem_date',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='midsem_date',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='deadline',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='last_date',
            field=models.DateField(),
        ),
    ]
