# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feeder06', '0010_auto_20161103_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='course_code',
            field=models.CharField(default='CS_207', max_length=10),
            preserve_default=False,
        ),
    ]
