# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feeder06', '0011_feedback_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='course_code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
