# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feeder06', '0012_deadline_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='course_code',
        ),
    ]
