# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feeder06', '0013_remove_deadline_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='running',
            field=models.BooleanField(default=True),
        ),
    ]
